// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZLEjLe8rMIHt955lkNvqeOa6XTc03j74',
    appId: '1:713020490317:web:271a5469674faffb8d9204',
    messagingSenderId: '713020490317',
    projectId: 'chat-appb-2d863',
    authDomain: 'chat-appb-2d863.firebaseapp.com',
    storageBucket: 'chat-appb-2d863.firebasestorage.app',
    measurementId: 'G-2T2YL5C3X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuFE_vBN-JfogNUSD7QZmS4V2OvVyqck',
    appId: '1:713020490317:android:47f673a7b62fd7fe8d9204',
    messagingSenderId: '713020490317',
    projectId: 'chat-appb-2d863',
    storageBucket: 'chat-appb-2d863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEWFfVmWpiADWsYgKHJeW4-4XmrERR4Qg',
    appId: '1:713020490317:ios:cc7c045deed5b0718d9204',
    messagingSenderId: '713020490317',
    projectId: 'chat-appb-2d863',
    storageBucket: 'chat-appb-2d863.firebasestorage.app',
    iosBundleId: 'com.example.chatAppb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEWFfVmWpiADWsYgKHJeW4-4XmrERR4Qg',
    appId: '1:713020490317:ios:cc7c045deed5b0718d9204',
    messagingSenderId: '713020490317',
    projectId: 'chat-appb-2d863',
    storageBucket: 'chat-appb-2d863.firebasestorage.app',
    iosBundleId: 'com.example.chatAppb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZLEjLe8rMIHt955lkNvqeOa6XTc03j74',
    appId: '1:713020490317:web:3939b55d044cdc318d9204',
    messagingSenderId: '713020490317',
    projectId: 'chat-appb-2d863',
    authDomain: 'chat-appb-2d863.firebaseapp.com',
    storageBucket: 'chat-appb-2d863.firebasestorage.app',
    measurementId: 'G-DNTDL0M7ZY',
  );
}
